INSERT INTO products (name, description, category, price) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with silent clicks', 'Electronics', 19.99),
('Mechanical Keyboard', 'Compact keyboard with tactile switches', 'Electronics', 79.90),
('USB-C Hub', 'Seven-in-one hub for laptop connectivity', 'Electronics', 34.50),
('4K Monitor', '27 inch monitor with vivid color output', 'Electronics', 289.00),
('Noise Cancelling Headphones', 'Over-ear headphones for focused work sessions', 'Electronics', 129.99),
('Office Chair', 'Adjustable chair with lumbar support', 'Furniture', 159.00),
('Standing Desk', 'Height-adjustable desk for healthier posture', 'Furniture', 349.99),
('Bookshelf', 'Minimalist wooden shelf with five levels', 'Furniture', 89.00),
('Desk Lamp', 'LED lamp with brightness control', 'Furniture', 24.75),
('Storage Cabinet', 'Two-door cabinet for office supplies', 'Furniture', 119.40),
('Running Shoes', 'Lightweight running shoes for daily training', 'Sports', 69.90),
('Yoga Mat', 'Non-slip mat with extra cushioning', 'Sports', 22.00),
('Dumbbell Set', 'Adjustable dumbbells for home workouts', 'Sports', 199.99),
('Tennis Racket', 'Balanced racket suitable for intermediate players', 'Sports', 84.20),
('Water Bottle', 'Insulated stainless steel bottle', 'Sports', 18.50),
('Coffee Beans', 'Medium roast whole beans with chocolate notes', 'Groceries', 12.99),
('Organic Tea', 'Green tea sachets with fresh aroma', 'Groceries', 8.40),
('Olive Oil', 'Extra virgin olive oil for everyday cooking', 'Groceries', 15.60),
('Protein Bars', 'Box of twelve peanut butter protein bars', 'Groceries', 21.50),
('Granola Pack', 'Honey almond granola breakfast pack', 'Groceries', 9.85),
('Notebook Set', 'Pack of three hardcover notebooks', 'Stationery', 14.25),
('Gel Pen Bundle', 'Smooth writing gel pens in assorted colors', 'Stationery', 6.90),
('Desk Organizer', 'Multi-slot organizer for workspace essentials', 'Stationery', 17.35),
('Planner 2026', 'Yearly planner with monthly and weekly views', 'Stationery', 11.80);
