CREATE TABLE IF NOT EXISTS products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)    NOT NULL,
    description VARCHAR(1000)   NOT NULL,
    category    VARCHAR(100)    NOT NULL,
    price       DECIMAL(12, 2)  NOT NULL
);
